# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [166]:
import numpy as np
array = np.arange(0,10)
array.resize(2,5)
array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [12]:
import numpy as np
array_1 = np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
array_2 = np.array([[1, 1, 1, 1, 1],[1, 1, 1, 1, 1]])
np.vstack([array, array_2])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [16]:
array1 = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
array2 = np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack([[array1], [array2]])

array([[[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [35]:
a = [[0,1,2], [3,4,5,6], [7,8,9]]
np.hstack(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [43]:
a = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11],[12, 13, 14]])
np.hstack(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [87]:
b = np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
b.reshape(5,3)




array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [114]:
arr = np.arange(25).reshape(5,5)
np.power(arr, 2)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [123]:
arr = np.arange(30).reshape(5,6)
np.mean(arr)


14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [121]:
arr = np.arange(30).reshape(5,6)
np.std(arr)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [122]:
arr = np.arange(30).reshape(5,6)
np.median(arr)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [124]:
arr = np.arange(30).reshape(5,6)
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [129]:
arr = np.arange(16).reshape(4,4)
np.trace(arr)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [169]:
arr = np.arange(4).reshape(2,2)
np.linalg.det(arr)

-2.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [175]:
arr = np.arange(35).reshape(7,5)
print ("Fifth Percentile is : ", float(np.percentile(arr, 5)))
print ("Ninty- Fifth Percentile is : ", float(np.percentile(arr, 95)))

Fifth Percentile is :  1.7000000000000002
Ninty- Fifth Percentile is :  32.3


## Question:15

### How to find if a given array has any null values?

In [165]:
arr = np.arange(35).reshape(7,5)
np.any(arr==0)


True